quote = [
    ["Technika cyfrowa jest naukowym dowodem na istnienie Boga. Bo to cud, że coś takiego w ogóle działa.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["100 ifów wygląda ohydnie.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Będę zliczał nieczytelne programy", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Komputer jest urządzeniem mogącym popełniać błędy szybciej niż jakikolwiek inny wynalazek w historii ludzkości... z wyjątkiem pistoletu.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Ten program nie dosć, że jest brzydki to jeszcze nie działa.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Programy mają wyglądać jak czysta matematyka.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Dzień bez napisania programu to dzień stracony.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Mieszanie gówna z miodem.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Te dane na wyjściu harcują.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Lubię kopce.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Hłe hłe hłe.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["Głupi użytkownik zawsze znajdzie dziurę w całym.", "prof. dr hab. inż. Jerzy Tyszer"],
    ["To skandal. Kolejny dowód na to, że system ten jest delikatnie mówiąc niedopracowany.", "prof. dr hab. inż. Ryszard Stasiński (o Moodlu)"],
    ["Będę klepaczem.", "dr inż. Filip Idzikowski"],
    ["Mówiliśmy o tym na zeszłym wykładzie, czyli dwa wykłady temu.", "dr hab. inż. Paweł Kryszkiewicz"],
    ["Każda z tych osób powinna napisać do mnie maila z prośbą o wpisanie oceny 2.0 za pierwszy termin. Wiem, że prośba dość oryginalna, ale pozwoli mi wystawić ocenę z poprawki.", "dr hab. inż. Paweł Kryszkiewicz"],
    ["Efekt blokowy najlepiej widać na udach.", "prof. dr hab. inż. Marek Domański"],
    ["Jedna z moich ostatnich podróży zagranicznych przed pandemią była związana z wizytą na znakomitej politechnice na Tajwanie ... zazwyczaj studenci nie mają możliwości przystępowania do egzaminów poprawkowych. Praktycznie nikt nie opuszcza uczelni po pierwszym stopniu. Tajwan eksportuje dużo elektroniki, a nie palet, mebli, jabłek itp.", "prof. dr hab. inż. Marek Domański"],
    ["Jeśli firma nie jest Microsoftem, to musi się bardzo z normami liczyć.", "prof. dr hab. inż. Marek Domański"],
    ["Widać, że nie widać.", "prof. dr hab. inż. Marek Domański"],
    ["Mój dziadek walczył w pierwszej wojnie światowej w pruskiej artylerii.", "prof. dr hab. inż. Marek Domański (o ciśnieniu fali akustycznej)"],
    ["Bezczelny abonent śmie dzwonić.", "prof. dr hab. inż. Wojciech Kabaciński"],
    ["Czasem jakiś szczur przegryzie światłowód. Tak się zdarza.", "dr inż. Janusz Kleban"],
    ["Czy Pan się widzi na przyszłym semestrze?", "dr inż. Janusz Kleban"],
    ["W tym momencie wyłączymy zasilanie.", "dr hab. inż. Paweł Szulakiewicz (chwilę przed opuszczeniem wykładu)"],
    ["Tu mamy procesor - główną jednostkę procesora.", "dr hab. inż. Paweł Szulakiewicz"],
    ["To jest całka", "mgr inż. Paweł Kubczak"],
    ["Czy Pani Jagoda jeszcze studiuje?", "dr inż. Jakub Pająkowski"],
    ["Umiecie wskaźniki prawda?", "mgr inż. Jakub Stankowski"],
    ["Nie wiem jak to zrobiliście, ale udało Wam się ustanowić nowy rekord w kategorii \"najgorsze wyniki z lab WDM\".", "mgr inż. Jakub Stankowski"],
    ["<siorbnięcie>", "dr inż. Andrzej Urbański"],
    ["Rosyjskie trolle", "dr inż. Adam Wojciechowski"],
    ["Ale ja tego nie zamawiałem.", "dr inż. Adam Wojciechowski"],
    ["Wszystkie modele są błędne, ale niektóre są użyteczne.", "prof. dr hab. inż. Mariusz Głąbowski"],
    ["O tym będziecie Państwo mówić na innych przedmiotach.", "dr hab. inż. Mieczysław Jessa"],
    ["Debugowanie warstwy fizycznej.", "dr hab. inż. Sławomir Hanczewski"],
    ["To wszyscy dzisiaj?", "dr hab. inż. Sławomir Hanczewski (o frekwencji)"],
    ["Pracujemy jako informatycy a nie wyznawcy komunikacji miejskiej.", "dr inż. Tomasz Koszlajda"],
    ["Jednym ze sposobów na posortowanie danych jest posortowanie danych.", "dr inż. Tomasz Koszlajda"],
    ["Nie ma autobusotramwajów.", "dr inż. Tomasz Koszlajda"],
    ["Ktoś by mógł w końcu coś dzisiaj zrozumieć.", "dr inż. Tomasz Koszlajda"],
    ["Mapy Google pozwalają na dostęp do serwerów z mapami.", "dr inż. Marcin Rodziewicz"],
    ["Na laboratoriach zrealizujemy wszystko co jest zaplanowane.", "dr inż. Jan Lamperski"],
    ["Kopiowanie to nic złego jeśli robi się to z głową.", "prof. dr hab. inż. Grzegorz Danilewicz"],
    ["Proszę dalej nie pogrążać grupy.", "dr hab. inż. Adrian Kliks"],
    ["Ok. TB.", "dr inż. Tomasz Bilski"],
    ["To politechnika więc muszę być trudne.", "dr inż. Damian Karwowski (o pytaniach na egzaminie"],
    ["Jaka jest szansa, że będziecie Państwo umieć coś więcej niż teraz? Moim zdaniem - niewielka.", "dr inż. Krzysztof Klimaszewski (o poprawie egzaminu)"],
    ["Jak Pan to obliczył?", "dr Agnieszka Ziemkowska-Siwek"],
    ["To by było nadużycie - wymagać od was takich prostych rzeczy.", "dr hab. inż. Maciej Wawrzyniak"],
    ["Śmiga jak Tyszer po kopcu.", "Autor nieznany"],
    ["Wojtek nie mogą włączyć kamer", "Autor nieznany"],
    ["Nie wiem co Państwo na ten temat wiecie, ale zakładam, że nic.", "Autor nieznany"]
]

ammount = quote.__len__()